version: "3"

services:
  app:
    build: .
    command: rails s -b '0.0.0.0'
    environment:
      - DATABASE_URL=postgres://${ALL_DATABASE_USERNAME}:${ALL_DATABASE_PASSWORD}@${ALL_DATABASE_HOST}:${ALL_DATABASE_PORT}/${ALL_DATABASE_NAME}
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${ALL_DATABASE_PASSWORD}
      - POSTGRES_USER=${ALL_DATABASE_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
